# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spider', '0006_auto_20190411_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7981\u7528')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u540d\u79f0')),
                ('priority', models.IntegerField(verbose_name='\u4f18\u5148\u7ea7')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '\u5f85\u63a8\u9001'), (2, '\u63a8\u9001\u4e2d'), (3, '\u5df2\u63a8\u9001')], default=1, verbose_name='\u72b6\u6001')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Linda')], default=1, verbose_name='\u76ee\u6807')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_channel_set', to='spider.Channel', verbose_name='\u9891\u9053')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_task_set', to='spider.Site', verbose_name='\u7ad9\u70b9')),
            ],
            options={
                'verbose_name': '\u4efb\u52a1',
                'verbose_name_plural': '\u4efb\u52a1',
            },
        ),
    ]
