# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Linda')], default=1, verbose_name='\u76ee\u6807'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '\u5f85\u63a8\u9001'), (2, '\u63a8\u9001\u4e2d')], default=1, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, '\u89c6\u9891')], default=1, verbose_name='\u7c7b\u578b'),
        ),
    ]
