# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0002_auto_20190411_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_channel_set', to='spider.Channel', verbose_name='\u9891\u9053'),
        ),
    ]
