# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0003_auto_20190411_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='process_num',
            field=models.IntegerField(default=1, verbose_name='\u8fdb\u7a0b\u6570'),
        ),
    ]
