# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0004_auto_20190412_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
    ]
