# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7981\u7528')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u9891\u9053',
                'verbose_name_plural': '\u9891\u9053',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7981\u7528')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u7ad9\u70b9',
                'verbose_name_plural': '\u7ad9\u70b9',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7981\u7528')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7981\u7528')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u540d\u79f0')),
                ('url', models.CharField(max_length=256, verbose_name='\u5730\u5740')),
                ('priority', models.IntegerField(verbose_name='\u4f18\u5148\u7ea7')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '\u5f85\u9886\u53d6'), (2, '\u6267\u884c\u4e2d')], default=1, verbose_name='\u72b6\u6001')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '\u5168\u91cf'), (2, '\u589e\u91cf')], default=1, verbose_name='\u7c7b\u578b')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Site', verbose_name='\u7ad9\u70b9')),
            ],
            options={
                'verbose_name': '\u4efb\u52a1',
                'verbose_name_plural': '\u4efb\u52a1',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7981\u7528')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('third_id', models.CharField(max_length=64, null=True, verbose_name='\u7b2c\u4e09\u65b9ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u540d\u79f0')),
                ('avatar', models.CharField(max_length=256, null=True, verbose_name='\u5934\u50cf')),
                ('description', models.CharField(max_length=256, null=True, verbose_name='\u63cf\u8ff0')),
                ('fans_num', models.IntegerField(null=True, verbose_name='\u7c89\u4e1d\u6570')),
                ('contact', models.CharField(max_length=256, null=True, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('address', models.CharField(max_length=256, null=True, verbose_name='\u5730\u5740')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Site', verbose_name='\u7ad9\u70b9')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spider.Task', verbose_name='\u4efb\u52a1')),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7981\u7528')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('third_id', models.CharField(max_length=64, null=True, verbose_name='\u7b2c\u4e09\u65b9ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u540d\u79f0')),
                ('cover', models.CharField(max_length=512, verbose_name='\u5c01\u9762')),
                ('url', models.CharField(max_length=512, verbose_name='\u64ad\u653e\u5730\u5740')),
                ('duration', models.IntegerField(null=True, verbose_name='\u65f6\u957f')),
                ('play_num', models.IntegerField(null=True, verbose_name='\u64ad\u653e\u6570')),
                ('like_num', models.IntegerField(null=True, verbose_name='\u559c\u6b22\u6570')),
                ('comment_num', models.IntegerField(null=True, verbose_name='\u8bc4\u8bba\u6570')),
                ('upload_time', models.DateTimeField(null=True, verbose_name='\u7528\u6237\u4e0a\u4f20\u65f6\u95f4')),
                ('oid', models.CharField(max_length=64, null=True, verbose_name='\u98ce\u884c\u56fe\u7247ID')),
                ('push_status', models.PositiveSmallIntegerField(choices=[(1, '\u5f85\u63a8\u9001'), (2, '\u63a8\u9001\u4e2d'), (3, '\u5df2\u63a8\u9001')], default=1, verbose_name='\u63a8\u9001\u72b6\u6001')),
                ('is_parse', models.BooleanField(default=False, verbose_name='\u662f\u5426\u89e3\u6790Url')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spider.Channel', verbose_name='\u9891\u9053')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Site', verbose_name='\u7ad9\u70b9')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spider.Task', verbose_name='\u4efb\u52a1')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spider.User', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u89c6\u9891',
                'verbose_name_plural': '\u89c6\u9891',
            },
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7981\u7528')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Tag', verbose_name='\u6807\u7b7e')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Video', verbose_name='\u89c6\u9891')),
            ],
            options={
                'verbose_name': '\u89c6\u9891\u4e0e\u6807\u7b7e',
                'verbose_name_plural': '\u89c6\u9891\u4e0e\u6807\u7b7e',
            },
        ),
    ]
