# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '\u5f85\u6267\u884c'), (2, '\u6267\u884c\u4e2d')], default=1, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='user',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spider.Task', verbose_name='\u4efb\u52a1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='third_id',
            field=models.CharField(max_length=64, null=True, verbose_name='\u7b2c\u4e09\u65b9ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spider.Task', verbose_name='\u4efb\u52a1'),
        ),
        migrations.AlterField(
            model_name='video',
            name='third_id',
            field=models.CharField(max_length=64, null=True, verbose_name='\u7b2c\u4e09\u65b9ID'),
        ),
    ]
