# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_control'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='day',
        ),
        migrations.RemoveField(
            model_name='control',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='control',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='control',
            name='month',
        ),
        migrations.RemoveField(
            model_name='control',
            name='num',
        ),
        migrations.RemoveField(
            model_name='control',
            name='week',
        ),
        migrations.AddField(
            model_name='control',
            name='cycle',
            field=models.CharField(max_length=64, null=True, verbose_name='\u6267\u884c\u5468\u671f'),
        ),
    ]
