# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_auto_20190402_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='desc',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=256, null=True, verbose_name='\u5934\u50cf'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=256, null=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AddField(
            model_name='user',
            name='fans_num',
            field=models.IntegerField(null=True, verbose_name='\u7c89\u4e1d\u6570'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '\u5f85\u9886\u53d6'), (2, '\u6267\u884c\u4e2d')], default=1, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=256, null=True, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=256, null=True, verbose_name='\u8054\u7cfb\u65b9\u5f0f'),
        ),
    ]
