# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_auto_20190409_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='site',
        ),
        migrations.RemoveField(
            model_name='user',
            name='task',
        ),
        migrations.RemoveField(
            model_name='video',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='video',
            name='site',
        ),
        migrations.RemoveField(
            model_name='video',
            name='task',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videotag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='videotag',
            name='video',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='VideoTag',
        ),
    ]
