# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0004_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, '\u589e\u91cf'), (1, '\u5168\u91cf')], default=0, verbose_name='\u7c7b\u578b'),
        ),
    ]
