# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0004_auto_20190410_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='system_info',
            field=models.CharField(max_length=64, null=True, verbose_name='\u7cfb\u7edf\u4fe1\u606f'),
        ),
    ]
