# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0005_control_system_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spider_task_set', to='spider.Site', verbose_name='\u7ad9\u70b9'),
        ),
    ]
