# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0006_auto_20190402_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='\u540d\u79f0'),
        ),
    ]
