# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0007_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, '\u5168\u91cf'), (1, '\u589e\u91cf')], default=0, verbose_name='\u7c7b\u578b'),
        ),
    ]
