# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0008_auto_20190402_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, '\u5168\u91cf'), (2, '\u589e\u91cf')], default=1, verbose_name='\u7c7b\u578b'),
        ),
    ]
