# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0009_auto_20190402_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_parse',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u89e3\u6790Url'),
        ),
    ]
